config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/novosti', to: 'static_pages#novosti', via: 'get'
  match '/drevniy', to: 'static_pages#drevniy', via: 'get'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def novosti
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      flash[:success] = "Welcome to the App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Happy Egypt"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div id="inner">
    
      <p>Проект HAPPY EGYPT by Kirill</p>
        
      
      <nav>
        <h2>Учусь создавать сайты на RAILS 4</h2>
      </nav>
    
  </div >
        
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Happy Egypt", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Главная", root_path %></li>
          
             <li id="fat-menu" class="dropdown">
              <a href="root_path" class="dropdown-toggle" data-toggle="dropdown">Всё о Египте<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Египет - удивительная страна!", novosti_path %></li>
                <li><%= link_to "Древний Египет", help_path %></li>
                <li><%= link_to "Курорты Египта", contact_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Последние новости",   about_path %></li>
              </ul>
            </li>                    
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Регистрация", signin_path %></li>
          <% end %>
          
          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="container2">
      <%= yield %>
      
      
    </div>
    
    <%= render 'layouts/footer' %>
   
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<%=  image_tag("Egypt.21.jpg", align:"right") %><h1>Последние новости Египта</h1><%=  image_tag("Egypt.05.jpg", align:"left") %>
<h2 class="zzz"> Знаменитую пирамиду Хеопса закрывают на ремонт, чтобы очистить от «наскальностей» туристов</br></br>
На реставрацию закроется одно из древнейших в мире сооружений, знаменитая достопримечательность Египта, пирамида Хеопса. При этом самой основной причиной для реставрации станут многочисленные порчи, оставленные здесь иностранными туристами.
Специалисты по сохранению культурного наследия Египта совместно с представителями министерства по делам древностей АРЕ после тщательного анализа ситуации пришли к выводу, что пирамида нуждается в срочной очистке от этих «памятников бескультурья». По оставленным на древних камнях именам можно судить о широкой географии египетского туризма - здесь отметились жители едва ли не со всего мира. Первые «заметки на память» были оставлены на пирамидах Гизы еще в XIX веке. Но в последние годы их стало очень много, хотя в большинстве случаев все эти письмена были нанесены мелом, ручками или маркерами.
Кроме реставрационных работ специалисты планируют полностью заменить систему освещения снаружи и внутри в соответствии с международными стандартами. Последний раз пирамиду Хеопса реставрировали 15 лет назад. Остальные знаменитые пирамиды Гизы подвергались ремонту около 2012 года.
Напомним, что это не единственный исторический памятник, регулярно страдающий от вандалов. Так, в ноябре «отличился» российский турист, который был задержан в Колизее за выцарапыванием на стене буквы «К» размером 25 см на 17 см. В итоге нарушитель был задержан, и ему предъявили обвинение в совершении акта вандализма со штрафом в размере €20 тыс.
<%=  image_tag("Egypt.20.jpg", align:"left") %>
</br></br>В Каире запустили водное такси </br></br>

По Нилу поплывут такси: новое развлечение предлагает туристам и всем желающим Каир. Столица Египта борется с пробками, которые станут одной из тем заседания Правительства страны на следующей неделе. Именно тогда должна развернуться широкая дискуссия по поводу пароходиков с шашечками, идею которых предложили министерства транспорта, гидромелиорации и окружающей среды. Речные такси призваны связать район Канатер-аль-Хайрия к северу от Каира с Хельваном, на противоположном конце города.<%=  image_tag("Egypt.22.jpg", align:"right") %>

По замыслу авторов идеи, речной трамвайчик будет делать 10 остановок и находиться в пути 45 минут. Согласитесь, это меньше часовой (а то и больше) езды на автомобиле.
Как сообщают источники в Министерстве гидромелиорации и водных ресурсов, всего за день такси будет совершать 15 поездок по Нилу. А Министр Хоссам Могази пообещал, что общее время в пути не превысит 20 минут. Первое речное такси отойдет от причала уже в январе.</h2>

app/views/static_pages/drevniy.html.erb

<h1>Египет </h1>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("1.jpg") %>
      <div class="carousel-caption">
	    
	    <p>1</p>
	  </div>
    </div>
    <div class="item">
      <%= image_tag("2.jpg") %>
      <div class="carousel-caption">
	    
	    <p>2</p>
	  </div>
    </div>
    <div class="item">
      <%= image_tag("3.jpg") %>
      <div class="carousel-caption">
	    
	    <p>3</p>
	  </div>
    </div>
    <div class="item">
      <%= image_tag("2.jpg") %>
      <div class="carousel-caption">
	    
	    <p>4</p>
	  </div>
    </div>
    <div class="item">
      <%= image_tag("1.jpg") %>
      <div class="carousel-caption">
	    
	    <p>5</p>
	  </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </a>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<%=  image_tag("Egypt.01.jpg", align:"right") %><h1>Древний Египет</h1>

<h2 class="zzz">Туризм является одной из основных доходных статей Египта[36], поэтому государство всячески способствует развитию этой отрасли. Интенсивно строятся и модернизируются курортные комплексы на морском побережье, в городах-курортах Шарм-эш-Шейх, Хургада и др.
В Египте находятся памятники различных эпох и цивилизаций: древнеегипетской, христианской (коптской), средневековой арабской. <%=  image_tag("Egypt.04.jpg", align:"left") %></br> Наиболее посещаемые достопримечательности:</br>
Древнеегипетские некрополи (пирамиды Гизы и другие, Долина Царей и Цариц в Луксоре, гробницы знати).
Храмы фараонов, особенно в Луксоре и Абу-Симбеле.
Памятники Средневековья — Исламский и Старый Каир.
На Красном и Средиземном морях расположены многочисленные курорты для любителей дайвинга, серфинга и тому подобных увлечений.</h2>
<%=  image_tag("Egypt.03.jpg", align:"right") %>
<h2 class="zzz">
Характерной особенностью египетского туризма является общение с местными жителями. Принятая здесь манера торговаться очень часто застает новичков врасплох[37]. Однако, во многом это — лишь обязательная часть спектакля, который традиционно разыгрывается между продавцом и покупателем. Завидев иностранца, местные торговцы могут существенно завышать цену, поэтому торговаться рекомендуется смело — с возгласами, демонстративными уходами и возвращениями. Следует также помнить, что, как и во многих местах скопления туристов, на улицах курортных городов есть мошенники и карманные воришки, поэтому необходимо внимательно следить за ценностями. <%=  image_tag("Egypt.07.jpg", align:"left") %> </br> Идёте фотографировать — берёте только фотоаппарат, идёте что-то покупать — берите небольшую сумму денег. В сложных ситуациях на помощь туристам придёт специальная туристическая полиция, куда следует обращаться для решения вопросов. Однако, несмотря на различия и особенности культур, отношение египтян к туристам очень радушное. Египет славится своим гостеприимством и тёплым отношением к путешественникам.</h2>

app/views/static_pages/home.html.erb
<div >
	<h1 class="z">Египетская сказка</h1>
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("Egypt.23.jpg") %>
      <!--<div class="carousel-caption">
	  </div> -->
    </div>
    <div class="item">
      <%= image_tag("Egypt.25.jpg") %>  
    </div>
    <div class="item">
      <%= image_tag("Egypt.24.jpg") %> 
    </div>
    
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </a>
</div>
	<div id="sidebarL">
	    <ul><h2>Популярные курорты Египта </h2>
		<li>Хургада</li>
		<li>Шарм-эль-Шейх</li>
		<li>Эль Гуна</li>
		<li>Сафага</li>
		<li>Макади Бей</li>
		<li>Каир</li>
		<li>Луксор</li>
		</ul>
		<h2 class="zzz">Хочешь получать новости о горящих турах в Египет?</h2>
		<%= link_to "Зарегистрируйся, и будите в курсе всех акций!", signup_path, class: "btn btn-large btn-primary" %>

	</div>
	<div id="content">
		<h2 >Блок новостей </h2>
		<h2 class="zzzz"><strong ><%= link_to "Знаменитую пирамиду Хеопса закрывают на ремонт, чтобы очистить от «наскальностей» туристов",   about_path %></strong></h2>
			<h2 class="zzz">
			На реставрацию закроется одно из древнейших в мире сооружений, знаменитая достопримечательность Египта, пирамида Хеопса. При этом самой основной причиной для реставрации станут многочисленные порчи, оставленные здесь иностранными туристами. Специалисты по сохранению культурного наследия Египта совместно с представителями министерства по делам древностей АРЕ после тщательного анализа ситуации пришли к выводу, что пирамида нуждается в срочной очистке от этих «памятников бескультурья».  </br></br>

			<strong><%= link_to "В Каире запустили водное такси",   about_path %></strong> </br></br>

			По Нилу поплывут такси: новое развлечение предлагает туристам и всем желающим Каир. Столица Египта борется с пробками, которые станут одной из тем заседания Правительства страны на следующей неделе. Именно тогда должна развернуться широкая дискуссия по поводу пароходиков с шашечками, идею которых предложили министерства транспорта, гидромелиорации и окружающей среды. Как сообщают источники в Министерстве гидромелиорации и водных ресурсов, всего за день такси будет совершать 15 поездок по Нилу. А Министр Хоссам Могази пообещал, что общее время в пути не превысит 20 минут. Первое речное такси отойдет от причала уже в январе.</h2>
	</div>
	
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        
        <%= @user.name %>
      </h1>
    </section>
    
  </aside>
  
  
</div>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>